# Generated by Django 4.1.4 on 2022-12-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestServerApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Date0fJoining',
            new_name='DateOfJoining',
        ),
    ]
